// FEATURE COMPATILITY VERSIONS
import { CONSTANTS as GLOBAL_CONSTANTS } from "git@github.com:requestly/requestly.git";

export const FEATURES = {
  RESPONSE_MAP_LOCAL: "RESPONSE_MAP_LOCAL",
  REQUEST_PAYLOAD_FILTER: "RESPONSE_DATA",
  ASYNC_MODIFY_RESPONSE_BODY: "ASYNC_MODIFY_RESPONSE_BODY",
  DESKTOP_APP_TERMINAL_PROXY: "DESKTOP_APP_TERMINAL_PROXY",
  DESKTOP_APP_SSL_PROXYING: "DESKTOP_APP_SSL_PROXYING",
  EXTENSION_GROUP_PIN_ICON: "EXTENSION_GROUP_PIN_ICON",
};

export const FEATURE_COMPATIBLE_VERSION = {
  [FEATURES.RESPONSE_MAP_LOCAL]: {
    [GLOBAL_CONSTANTS.APP_MODES.DESKTOP]: "0.0.29-beta",
    [GLOBAL_CONSTANTS.APP_MODES.EXTENSION]: null,
  },
  [FEATURES.REQUEST_PAYLOAD_FILTER]: {
    [GLOBAL_CONSTANTS.APP_MODES.DESKTOP]: "0.0.30-beta",
    [GLOBAL_CONSTANTS.APP_MODES.EXTENSION]: "22.1.12",
  },
  [FEATURES.ASYNC_MODIFY_RESPONSE_BODY]: {
    [GLOBAL_CONSTANTS.APP_MODES.DESKTOP]: null,
    [GLOBAL_CONSTANTS.APP_MODES.EXTENSION]: null,
  },
  [FEATURES.DESKTOP_APP_TERMINAL_PROXY]: {
    [GLOBAL_CONSTANTS.APP_MODES.DESKTOP]: "1.1.0",
    [GLOBAL_CONSTANTS.APP_MODES.EXTENSION]: null,
  },
  [FEATURES.DESKTOP_APP_SSL_PROXYING]: {
    [GLOBAL_CONSTANTS.APP_MODES.DESKTOP]: "1.2.0",
    [GLOBAL_CONSTANTS.APP_MODES.EXTENSION]: null,
  },
  [FEATURES.EXTENSION_GROUP_PIN_ICON]: {
    [GLOBAL_CONSTANTS.APP_MODES.DESKTOP]: null,
    [GLOBAL_CONSTANTS.APP_MODES.EXTENSION]: "23.0.0",
  },
};
