import FEATURES from "./sub/features";
import LINKS from "./sub/links";
import PATHS from "./sub/paths";
import MARKETPLACE_TABLE_CONSTANTS from "./sub/marketplace-table-constants";
import RULE_EDITOR_CONFIG from "./sub/rule-editor";
import RULE_TYPES_CONFIG from "./sub/rule-types";
import RULES_LIST_TABLE_CONSTANTS from "./sub/rules-list-table-constants";
import MOCK_TYPES_CONFIG from "./sub/mock-types";
import { STATUS_CODE_OPTIONS } from "./sub/statusCode";
import { CONTENT_TYPE_OPTIONS } from "./sub/contentType";
import { METHOD_TYPE_OPTIONS } from "./sub/methodType";
import SHARED_LISTS_TABLE_CONSTANTS from "./sub/shared-lists-table-constants";
import FILES_TABLE_CONSTANTS from "./sub/files-table-constants";
import THEME_COLORS from "./sub/theme-colors";
import AUTH from "./sub/auth";
import PRICING from "./sub/pricing";
import LIMIT_REACHED_MODAL from "./sub/limit-reached-modal";
import EMAIL_DOMAINS from "./sub/email-domains";
import STYLES from "./sub/styles";
import COOKIES from "./sub/cookies";
import THEMES from "./sub/themes";

const APP_CONSTANTS = {};

/** FEATURES */
APP_CONSTANTS.FEATURES = FEATURES;

/** PRICING */
APP_CONSTANTS.PRICING = PRICING;

/** STORAGE KEYS */
APP_CONSTANTS.MIGRATED_TO_NEW_UI = "migrated-to-new-ui";
APP_CONSTANTS.STORAGE_MIGRATED_TO_LOCAL = "storage-migrated-to-local";
APP_CONSTANTS.LAST_BACKUP_TIMESTAMP = "last-backup-timestamp";
APP_CONSTANTS.LAST_SYNC_TIMESTAMP = "last-synced-on";
APP_CONSTANTS.RQ_SETTINGS = "rq_settings";

/** EXTERNAL LINKS */
APP_CONSTANTS.LINKS = LINKS;

/** CUSTOM STYLES */
APP_CONSTANTS.STYLES = STYLES;

/** APP THEME */
APP_CONSTANTS.THEMES = THEMES;

/** CONFIG FOR RULE EDITOR */
APP_CONSTANTS.RULE_EDITOR_CONFIG = RULE_EDITOR_CONFIG;

/** PATHS */
APP_CONSTANTS.PATHS = PATHS;

/** RULE TYPES CONFIG */
APP_CONSTANTS.RULE_TYPES_CONFIG = RULE_TYPES_CONFIG;

/** CONFIG FOR RULE LIST TABLE */
APP_CONSTANTS.RULES_LIST_TABLE_CONSTANTS = RULES_LIST_TABLE_CONSTANTS;

/** MOCK TYPES CONFIG */
APP_CONSTANTS.MOCK_TYPES_CONFIG = MOCK_TYPES_CONFIG;
APP_CONSTANTS.STATUS_CODE = STATUS_CODE_OPTIONS;
APP_CONSTANTS.CONTENT_TYPE = CONTENT_TYPE_OPTIONS;
APP_CONSTANTS.METHOD_TYPE = METHOD_TYPE_OPTIONS;

/** CONFIG FOR SHARED LISTS TABLE */
APP_CONSTANTS.SHARED_LISTS_TABLE_CONSTANTS = SHARED_LISTS_TABLE_CONSTANTS;

/**  CONFIG FOR MARKETPLACE TABLE */
APP_CONSTANTS.MARKETPLACE_TABLE_CONSTANTS = MARKETPLACE_TABLE_CONSTANTS;

/** CONFIG FOR FILES TABLE */
APP_CONSTANTS.FILES_TABLE_CONSTANTS = FILES_TABLE_CONSTANTS;

/** GLOBAL THEME COLORS */
APP_CONSTANTS.THEME_COLORS = THEME_COLORS;

/** AUTHENTICATION */
APP_CONSTANTS.AUTH = AUTH;

/** LIMIT REACHED MODAL */
APP_CONSTANTS.LIMIT_REACHED_MODAL = LIMIT_REACHED_MODAL;

//MISC
APP_CONSTANTS.NOTIFICATION_DURATION = 2000;
APP_CONSTANTS.DELAY_COMPATIBILITY_VERSION = "21.6.4";
APP_CONSTANTS.EXECUTION_LOGS_COMPATIBILITY_VERSION = "21.11.16";
APP_CONSTANTS.MOCK_RESPONSE_BODY_CHARACTER_LIMIT = 800000;
APP_CONSTANTS.TRASH_DURATION_OF_DELETED_RULES_TO_SHOW = 30;
APP_CONSTANTS.BETA = "beta";
APP_CONSTANTS.LOCAL = "local";
APP_CONSTANTS.PROD = "prod";

//RULES LIMIT
APP_CONSTANTS.NO_LOGIN_RULES_LIMIT = 3;

// LIST OF PERSONAL EMAIL DOMAINS
APP_CONSTANTS.EMAIL_DOMAINS = EMAIL_DOMAINS;

// Trial Mode related
//List of countries to implement free trial- Brazil, France, Japan, Canada
APP_CONSTANTS.FREE_TRIAL_COUNTRIES = ["BR", "FR", "JP", "CA"];
APP_CONSTANTS.TRIAL_MODE_START_DATE = "2022-02-28";

// SYNCING TEST
APP_CONSTANTS.APLHA_TEST_EMAIL_DOMAINS = ["rq.io", "requestly.io"];
APP_CONSTANTS.APLHA_TEST_EMAILS = [
  "requestly.extension@gmail.com",
  "nafees87n@gmail.com",
];

// COOKIES
APP_CONSTANTS.COOKIES = COOKIES;

// Desktop App
// Controls the blocking update dialog
APP_CONSTANTS.DESKTOP_APP_MIN_COMPATIBLE_VERSION = "1.1.2";

export default APP_CONSTANTS;
